version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/tunepolo/github_star_importer
    docker:
      - image: circleci/golang:1.13

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make deps
      - run: make build
      - run: make test

workflows:
  continuous-integration:
    jobs:
      - test
