version: 2.1

orbs:
  reviewdog: timakin/reviewdog@0.2.0

executors:
  default:
    working_directory: /go/src/github.com/tunepolo/github_star_importer
    docker:
      - image: circleci/golang:1.11

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make
      - run: make test
  review:
    executor:
      name: default
    steps:
      - checkout
      - reviewdog/review:
          linters: "golang.org/x/lint/golint github.com/kisielk/errcheck"

workflows:
  continuous-integration:
    jobs:
      - test
      - review:
          context: reviewdog
          filters:
            branches:
              ignore:
                - master
