version: 2.1

executors:
  default:
    working_directory: /go/src/github.com/tunepolo/github_star_importer
    docker:
      - image: circleci/golang:1.11

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

workflows:
  continuous-integration:
    jobs:
      - test
